// svelte/src/App.svelte
<script lang="ts">
  import Processes from "./components/Processes.svelte";
  import Resources from "./components/Resources.svelte";
  import Sidebar from "./components/Sidebar.svelte";

  let active: string = "processes";
</script>

<main class="container mx-auto">
  <Sidebar on:active={(event) => (active = event.detail)} />
  <div class="ml-20 p-4">
    <!-- <h1 class="test-3xl font-bold underline">Sysinfo UI</h1> -->
    {#if active == "processes"}
      <Processes />
    {:else if active == "resources"}
      <Resources />
    {/if}
  </div>
</main>

// vue/src/App.vue
<script setup lang="ts">
import Processes from "./components/Processes.vue";
import Resources from "./components/Resources.vue";
import Sidebar from "./components/Sidebar.vue";
import { ref } from 'vue';

const active = ref("processes");
</script>

<template>
  <main class="container mx-auto">
    <Sidebar @active="(v: string) => active = v" />
    <div class="ml-20 p-4">
      <Processes v-if="active == 'processes'" />
      <Resources v-else-if="active == 'resources'" />
    </div>
  </main>
</template>
