// vue/src/App.vue
<script setup lang="ts">
import Processes from "./components/Processes.vue";
import Resources from "./components/Resources.vue";
import Sidebar from "./components/Sidebar.vue";
import { ref } from 'vue';

const active = ref("processes");
</script>

<template>
  <main class="container mx-auto">
    <Sidebar @active="(v: string) => active = v" />
    <div class="ml-20 p-4">
      <Processes v-if="active == 'processes'" />
      <Resources v-else-if="active == 'resources'" />
    </div>
  </main>
</template>

// solid/src/App.tsx
import { Match, Switch, createSignal } from "solid-js";
import Processes from "./components/Processes";
import Resources from "./components/Resources";
import Sidebar from "./components/Sidebar";

export default function App() {
  const [active, setActive] = createSignal("processes");

  return (
    <main class="container mx-auto">
      <Sidebar onActive={setActive} />
      <div class="ml-20 p-4">
        <Switch>
          <Match when={active() == "processes"}>
            <Processes />
          </Match>
          <Match when={active() == "resources"}>
            <Resources />
          </Match>
        </Switch>
      </div>
    </main>
  );
}
